
import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Adrianna Flat Sandal - Pastel Pink',
    category: 'Sandals',
    gender: 'Girl',
    type: 'Sandal',
    price: 449,
    originalPrice: 499,
    discount: 10,
    rating: 4.5,
    reviews: 128,
    sizes: [5, 6, 7, 8],
    colors: ['Pink', 'White'],
    imageUrl: 'https://images.unsplash.com/photo-1515347619252-60a4bdad8880?auto=format&fit=crop&q=80&w=800',
    isNew: true,
  },
  {
    id: '2',
    name: 'Bonito Floater - Adventure Blue',
    category: 'Floaters',
    gender: 'Boy',
    type: 'Floater',
    price: 699,
    originalPrice: 899,
    discount: 22,
    rating: 4.8,
    reviews: 85,
    sizes: [7, 8, 9, 10, 11],
    colors: ['Blue', 'Black'],
    imageUrl: 'https://images.unsplash.com/photo-1603191659812-ee978eeeef76?auto=format&fit=crop&q=80&w=800',
    isNew: false,
  },
  {
    id: '3',
    name: 'Walk n Style Sparkle Party Wear',
    category: 'Sandals',
    gender: 'Girl',
    type: 'Sandal',
    price: 799,
    originalPrice: 999,
    discount: 20,
    rating: 4.2,
    reviews: 45,
    sizes: [6, 7, 8, 9],
    colors: ['Gold', 'Silver'],
    imageUrl: 'https://images.unsplash.com/photo-1562183241-b937e95585b6?auto=format&fit=crop&q=80&w=800',
    isNew: true,
  },
  {
    id: '4',
    name: 'Dino-Step Rubber Clogs',
    category: 'Clogs',
    gender: 'Unisex',
    type: 'Clog',
    price: 399,
    originalPrice: 499,
    discount: 20,
    rating: 4.6,
    reviews: 210,
    sizes: [4, 5, 6, 7],
    colors: ['Green', 'Yellow'],
    imageUrl: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&q=80&w=800',
    isNew: false,
  },
  {
    id: '5',
    name: 'Urban Explorer Sporty Sandal',
    category: 'Sandals',
    gender: 'Boy',
    type: 'Sandal',
    price: 549,
    originalPrice: 649,
    discount: 15,
    rating: 4.3,
    reviews: 67,
    sizes: [8, 9, 10, 11, 12, 13],
    colors: ['Navy', 'Red'],
    imageUrl: 'https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&q=80&w=800',
    isNew: false,
  },
  {
    id: '6',
    name: 'Little Princess Bow Flat',
    category: 'Sandals',
    gender: 'Girl',
    type: 'Sandal',
    price: 899,
    originalPrice: 1199,
    discount: 25,
    rating: 4.9,
    reviews: 32,
    sizes: [5, 6, 7],
    colors: ['Red', 'Pink'],
    imageUrl: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&q=80&w=800',
    isNew: true,
  },
  {
    id: '7',
    name: 'Active-Play Daily Floater',
    category: 'Floaters',
    gender: 'Unisex',
    type: 'Floater',
    price: 499,
    originalPrice: 599,
    discount: 16,
    rating: 4.0,
    reviews: 156,
    sizes: [6, 7, 8, 9, 10],
    colors: ['Grey', 'Black'],
    imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&q=80&w=800',
    isNew: false,
  },
  {
    id: '8',
    name: 'Comfy-Soft Velcro Sandal',
    category: 'Sandals',
    gender: 'Boy',
    type: 'Sandal',
    price: 599,
    originalPrice: 799,
    discount: 25,
    rating: 4.4,
    reviews: 89,
    sizes: [7, 8, 9, 10],
    colors: ['Brown', 'Black'],
    imageUrl: 'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?auto=format&fit=crop&q=80&w=800',
    isNew: false,
  }
];

export const COLORS = ['Red', 'Pink', 'Blue', 'Black', 'Brown', 'Navy', 'Grey', 'Green', 'Yellow', 'Gold', 'Silver', 'White'];
export const SIZES = [4, 5, 6, 7, 8, 9, 10, 11, 12, 13];
export const GENDERS = ['Boy', 'Girl', 'Unisex'];
export const SHOE_TYPES = ['Sandal', 'Floater', 'Clog', 'Flip-Flop'];
